#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_8bit_storage : require

layout(local_size_x = 1, local_size_y = 1) in;

layout( push_constant ) uniform constants
{
    int y_max;
    int x;
    int z;
    int chunk;
} p;

layout(std430, binding = 0) buffer lay1 { int8_t dest[]; };

void main()
{
    const uint y = gl_GlobalInvocationID.x;
    if (p.y_max < 64 && y > p.y_max)
        dest[((y * 256) + (p.z * 16) + p.x) + (p.chunk * 98304)] = int8_t(2);
    else
        dest[((y * 256) + (p.z * 16) + p.x) + (p.chunk * 98304)] = int8_t(1);
}