#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_8bit_storage : require

layout(local_size_x = 16, local_size_y = 16) in;

layout( push_constant ) uniform constants
{
    int x;
    int z;
    int chunk;
    float seed;
} p;

layout(std430, binding = 0) buffer lay1 { int8_t dest[]; };

float random (in vec2 st, float seed) 
{
    float safe_seed = mod(seed, 10000.0);
    
    vec2 offset_st = st + vec2(safe_seed, safe_seed * 1.234); 
    
    return fract(sin(dot(offset_st, vec2(12.9898,78.233))) * 43758.5453123);
}

// Based on Morgan McGuire @morgan3d
// https://www.shadertoy.com/view/4dS3Wd
float noise (in vec2 st, float seed)
{
    vec2 i = floor(st);
    vec2 f = fract(st);

    // Four corners in 2D of a tile
    float a = random(i, seed);
    float b = random(i + vec2(1.0, 0.0), seed);
    float c = random(i + vec2(0.0, 1.0), seed);
    float d = random(i + vec2(1.0, 1.0), seed);

    vec2 u = f * f * (3.0 - 2.0 * f);

    float n = mix(a, b, u.x) +
            (c - a)* u.y * (1.0 - u.x) +
            (d - b) * u.x * u.y;
    
    return (n * 2.0) - 1.0;
}

float fbm (in vec2 st, int octave, float seed) {
    // Initial values
    float value = 0.0;
    float amplitude = .5;
    float frequency = 0.;
    //
    // Loop of octaves
    for (int i = 0; i < octave; i++) 
    {
        value += amplitude * noise(st, seed);
        st *= 2.;
        amplitude *= .5;
    }
    return value;
}

float map(float value, float inMin, float inMax, float outMin, float outMax) 
{
    return outMin + (value - inMin) * (outMax - outMin) / (inMax - inMin);
}

float getContinentalness(float noise) 
{
    if (noise < -0.8f) 
    { 
        return map(noise, -1.0f, -0.8f, 10.0f, 40.0f);
    } 
    else if (noise < -0.5f) 
    {
        return map(noise, -0.8f, -0.5f, 40.0f, 45.0f);
    } 
    else if (noise < -0.3f) 
    {
        return map(noise, -0.5f, -0.3f, 45.0f, 64.0f);
    } 
    else if (noise < 0.5f)
    {
        return map(noise, -0.3f, 0.5f, 64.0f, 90.0f);
    } 
    else if (noise < 0.7f) 
    {
        return map(noise, 0.5f, 0.7f, 90.0f, 120.0f);
    } 
    else if (noise < 0.9f) 
    {
        return map(noise, 0.7f, 0.9f, 120.0f, 170.0f);
    } 
    else 
    {
        return map(noise, 0.9f, 1.01f, 170.0f, 250.0f);
    }
}

float mod289(float x){return x - floor(x * (1.0 / 289.0)) * 289.0;}
vec4 mod289(vec4 x){return x - floor(x * (1.0 / 289.0)) * 289.0;}
vec4 perm(vec4 x){return mod289(((x * 34.0) + 1.0) * x);}

float noise3(vec3 p, float seed)
{

    float safe_seed = mod(seed, 10000.0);

    vec3 a = floor(p);
    vec3 d = p - a;
    d = d * d * (3.0 - 2.0 * d);

    vec4 b = a.xxyy + vec4(0.0, 1.0, 0.0, 1.0);
    vec4 k1 = perm(b.xyxy);
    vec4 k2 = perm(k1.xyxy + b.zzww);

    vec4 c = k2 + a.zzzz;
    vec4 k3 = perm(c);
    vec4 k4 = perm(c + 1.0);

    vec4 o1 = fract(k3 * (1.0 / 41.0));
    vec4 o2 = fract(k4 * (1.0 / 41.0));

    vec4 o3 = o2 * d.z + o1 * (1.0 - d.z);
    vec2 o4 = o3.yw * d.x + o3.xz * (1.0 - d.x);

    return o4.y * d.y + o4.x * (1.0 - d.y);
}

#define NUM_OCTAVES 2
float fbm3(vec3 x, float seed) 
{
	float v = 0.0;
	float a = 0.5;
	vec3 shift = vec3(100);
	for (int i = 0; i < NUM_OCTAVES; ++i) {
		v += a * noise3(x, seed);
		x = x * 2.0 + shift;
		a *= 0.5;
	}
	return v;
}

void main()
{
    const int x = p.x * 16 + int(gl_LocalInvocationID.x);
    const int z = p.z * 16 + int(gl_LocalInvocationID.y);

    float val = fbm(vec2(x * 0.003221649073064327, z * 0.00322164907306432), 6,p.seed);
    
    int y_max = int(getContinentalness(val)) + 64;

    float temp = fbm(vec2(float(x) * 0.0005221649073064327, float(z) * 0.000522164907306432),16, p.seed);


    for (int y = 0; y < y_max - 3; y++)
    {
        float val2 = fbm3(vec3(x * 0.041f, y * 0.05f, z * 0.041f), p.seed);
        if (val2 > 0.2)
        {
            dest[((y * 256) + (gl_LocalInvocationID.y * 16) + gl_LocalInvocationID.x) + (p.chunk * 98304)] = int8_t(1);
        }
    }
}